### ISSUE TITLE
Added to custom distro, but have to pacman-key --populate chaotic

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/pkgbuild-chaotic-keyring#8]
I wanted to see if I can get some help with this. If you think it is not meant for here, please close the issue I do not mind.

We have a custom distro (TROMjaro) and we want to add the chaotic-aur repo. So far so good. We built this package + chaotic-mirrorlist. Added to the distro. Added the repo to `etc/pacman.conf`. All good. After the distro is compiled I can see all of the packages from chaotic. Problem is, when I try to install any I get a "signature is unknown trust" error. The only way to fix it is to "sudo pacman-key --populate chaotic". I wonder why since such things should be taken car of by this package, correct?

Any guidance?

Thank you very much for this repo and your work!

**Comment by tio-trom** [comment]
To be more specific this is the error I am getting: `invalid or corrupted package (PGP signature):`
```
Download of glaxnimate (0.5.0_1_g49002eec-1) finished
Checking keyring...
Downloading required keys...
Checking integrity...
Error: glaxnimate: signature from "Nico Jensch (Chaotic-AUR) <dr460nf1r3@garudalinux.org>" is unknown trust
Removing invalid files and retrying...
Resolving dependencies...
Checking inter-conflicts...
Download of glaxnimate (0.5.0_1_g49002eec-1) started
Download of glaxnimate (0.5.0_1_g49002eec-1) finished
Checking keyring...
Checking integrity...
Error: glaxnimate: signature from "Nico Jensch (Chaotic-AUR) <dr460nf1r3@garudalinux.org>" is unknown trust
Failed to commit transaction:
invalid or corrupted package (PGP signature):
```

**Comment by PedroHLC** [comment]
You probably have some other packages which in its "hooks" is removing the pacman's gnupg-database and creating it from 0. Check for other *-keyring packages you have installed.

**Comment by tio-trom** [comment]
Thanks. Indeed there is `gnome-keyring` but I wonder what's the solution to this conundrum :D . My solution for now was to add a hook to pacman to do `sudo pacman-key --populate chaotic` everytime a package is installed/removed/updated. This way it forces the keyring. Would this be a bad practice? Would that command ping your servers too many times?

Sorry if this is offtopic is ok we can close it and we will deal with it. At first I thought it may be something you can add to the package itself for such situations.

**Comment by PedroHLC** [comment]
@tio-trom in case you want more information, feel free to contact us through Telegram or Matrix (links in [our homepage](https://aur.chaotic.cx))

**Comment by tio-trom** [comment]
> @tio-trom in case you want more information, feel free to contact us through Telegram or Matrix (links in [our homepage](https://aur.chaotic.cx))

Thank you very much! I have indeed kinda found a fix for it.
